### Build Stage ###
FROM gradle:8.13.0-jdk21 AS builder

WORKDIR /app

COPY api-server/build.gradle api-server/settings.gradle ./

COPY api-server/gradle ./gradle

COPY api-server/src ./src

RUN gradle bootJar -x test --no-daemon --parallel --console=plain

### Run Stage ###
FROM openjdk:21-jdk-slim

WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
